version: '3.8'

services:
  front:
    build: 
      context: .
      args:
        WORKDIR: $WORKDIR
    command: yarn serve
    volumes:
      - ./:/$WORKDIR
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
